### ISSUE TITLE
Can not use ecto multy

### ISSUE THREAD

**Issue by Slavenin** [clickhouse-elixir/clickhouse_ecto#13]
Hi!
When i try insert records throught `Ecto.Multi` i have a error:
```
** (FunctionClauseError) no function clause matching in Ecto.Schema.safe_load_zip/4    
    
    The following arguments were given to Ecto.Schema.safe_load_zip/4:
    
        # 1
        [] 
    
        # 2
        [1]
    
        # 3
        %Schema.Coins{
          __meta__: #Ecto.Schema.Metadata<:built, "coins">,
          block: nil,
          symbol: nil,
          timestamp: nil,
          txn: nil,
          type: nil,
          volume: nil
        }
    
        # 4
        #Function<23.31199312/2 in Ecto.Repo.Schema.postprocess/5>
    
    Attempted function clauses (showing 2 out of 2):
    
        defp safe_load_zip([{field, type} | fields], [value | values], struct, loader)
        defp safe_load_zip([], [], _struct, _loader)
    
    (ecto) lib/ecto/schema.ex:1442: Ecto.Schema.safe_load_zip/4
    (ecto) lib/ecto/schema.ex:1431: Ecto.Schema.__safe_load__/6
    (ecto) lib/ecto/repo/schema.ex:65: anonymous fn/7 in Ecto.Repo.Schema.postprocess/5
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/repo/schema.ex:64: Ecto.Repo.Schema.postprocess/5
    (ecto) lib/ecto/repo/schema.ex:53: Ecto.Repo.Schema.do_insert_all/7
    (ecto) lib/ecto/multi.ex:441: Ecto.Multi.apply_operation/4
    (ecto) lib/ecto/multi.ex:421: Ecto.Multi.apply_operation/5
```
Records sucessfuly added to the table, but after that - raise error.

Simple code snippet
```elixir
list = 
[
  %{
    block: 1194660,
    symbol: "PCOALERT",
    timestamp: ~U[2019-07-24 11:51:34Z],
    txn: 963116,
    type: 1,
    volume: #Decimal<3698.562602227655288279>
  },
  %{
    block: 1194660,
    symbol: "POPE",
    timestamp: ~U[2019-07-24 11:51:34Z],
    txn: 963116,
    type: 2,
    volume: #Decimal<0.380456477496956849>
  },
  %{
    block: 1194657,
    symbol: "BIP",
    timestamp: ~U[2019-07-24 11:51:19Z],
    txn: 963114,
    type: 1,
    volume: #Decimal<13.871965040627080734>
  }
]

Ecto.Multi.new()
        |> Ecto.Multi.insert_all(:insert_all, Coins, list)
        |> Repo.transaction()
```

**Comment by froggrog** [comment]
I have the same problem ((

**Comment by blatyo** [comment]
Clickhouse doesn't support transactions. So, you should avoid trying to use transactions.
